
export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  verses: number;
}

export const surahs: Surah[] = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', verses: 7 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', verses: 286 },
  { number: 3, name: 'Ali Imran', arabicName: 'آل عمران', verses: 200 },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', verses: 176 },
  { number: 5, name: 'Al-Maidah', arabicName: 'المائدة', verses: 120 },
  { number: 6, name: 'Al-Anam', arabicName: 'الأنعام', verses: 165 },
  { number: 7, name: 'Al-Araf', arabicName: 'الأعراف', verses: 206 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', verses: 75 },
  { number: 9, name: 'At-Taubah', arabicName: 'التوبة', verses: 129 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', verses: 109 },
  { number: 11, name: 'Hud', arabicName: 'هود', verses: 123 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', verses: 111 },
  { number: 13, name: 'Ar-Rad', arabicName: 'الرعد', verses: 43 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', verses: 52 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', verses: 99 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', verses: 128 },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', verses: 111 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', verses: 110 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', verses: 98 },
  { number: 20, name: 'Ta-Ha', arabicName: 'طه', verses: 135 },
  { number: 21, name: 'Al-Anbiya', arabicName: 'الأنبياء', verses: 112 },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', verses: 78 },
  { number: 23, name: 'Al-Muminun', arabicName: 'المؤمنون', verses: 118 },
  { number: 24, name: 'An-Nur', arabicName: 'النور', verses: 64 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', verses: 77 },
  { number: 26, name: 'Ash-Shuara', arabicName: 'الشعراء', verses: 227 },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', verses: 93 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', verses: 88 },
  { number: 29, name: 'Al-Ankabut', arabicName: 'العنكبوت', verses: 69 },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', verses: 60 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', verses: 34 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', verses: 30 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', verses: 73 },
  { number: 34, name: 'Saba', arabicName: 'سبأ', verses: 54 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', verses: 45 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', verses: 83 },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', verses: 182 },
  { number: 38, name: 'Sad', arabicName: 'ص', verses: 88 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', verses: 75 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', verses: 85 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', verses: 54 },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', verses: 53 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', verses: 89 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', verses: 59 },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', verses: 37 },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', verses: 35 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', verses: 38 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', verses: 29 },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', verses: 18 },
  { number: 50, name: 'Qaf', arabicName: 'ق', verses: 45 },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', verses: 60 },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', verses: 49 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', verses: 62 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', verses: 55 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', verses: 78 },
  { number: 56, name: 'Al-Waqiah', arabicName: 'الواقعة', verses: 96 },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', verses: 29 },
  { number: 58, name: 'Al-Mujadila', arabicName: 'المجادلة', verses: 22 },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', verses: 24 },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', verses: 13 },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', verses: 14 },
  { number: 62, name: 'Al-Jumuah', arabicName: 'الجمعة', verses: 11 },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', verses: 11 },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', verses: 18 },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', verses: 12 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', verses: 12 },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', verses: 30 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', verses: 52 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', verses: 52 },
  { number: 70, name: 'Al-Maarij', arabicName: 'المعارج', verses: 44 },
  { number: 71, name: 'Nuh', arabicName: 'نوح', verses: 28 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', verses: 28 },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', verses: 20 },
  { number: 74, name: 'Al-Muddathir', arabicName: 'المدثر', verses: 56 },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', verses: 40 },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', verses: 31 },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', verses: 50 },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', verses: 40 },
  { number: 79, name: 'An-Naziat', arabicName: 'النازعات', verses: 46 },
  { number: 80, name: 'Abasa', arabicName: 'عبس', verses: 42 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', verses: 29 },
  { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', verses: 19 },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', verses: 36 },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', verses: 25 },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', verses: 22 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', verses: 17 },
  { number: 87, name: 'Al-Ala', arabicName: 'الأعلى', verses: 19 },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', verses: 26 },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', verses: 30 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', verses: 20 },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', verses: 15 },
  { number: 92, name: 'Al-Lail', arabicName: 'الليل', verses: 21 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', verses: 11 },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', verses: 8 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', verses: 8 },
  { number: 96, name: 'Al-Alaq', arabicName: 'العلق', verses: 19 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', verses: 5 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', verses: 8 },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', verses: 8 },
  { number: 100, name: 'Al-Adiyat', arabicName: 'العاديات', verses: 11 },
  { number: 101, name: 'Al-Qariah', arabicName: 'القارعة', verses: 11 },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', verses: 8 },
  { number: 103, name: 'Al-Asr', arabicName: 'العصر', verses: 3 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', verses: 9 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', verses: 5 },
  { number: 106, name: 'Quraish', arabicName: 'قريش', verses: 4 },
  { number: 107, name: 'Al-Maun', arabicName: 'الماعون', verses: 7 },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', verses: 3 },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', verses: 6 },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', verses: 3 },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', verses: 5 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', verses: 4 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', verses: 5 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', verses: 6 }
];

export const getSurahByName = (name: string): Surah | undefined => {
  return surahs.find(surah => surah.name === name);
};

export const calculateMemorizationStatus = (actual: number, target: number): { status: string; color: string } => {
  const percentage = Math.min((actual / target) * 100, 100);
  
  if (percentage === 100) {
    return { status: 'Fully Achieved', color: 'bg-green-100 text-green-800' };
  } else if (percentage >= 75) {
    return { status: 'Achieved', color: 'bg-yellow-100 text-yellow-800' };
  } else {
    return { status: 'Not Achieved', color: 'bg-red-100 text-red-800' };
  }
};
