// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvqkohfljkborimawqll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cWtvaGZsamtib3JpbWF3cWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjA2NTgsImV4cCI6MjA2NzQzNjY1OH0.uyw2sC-6Ps3j6rbB9DsmyRTJ6EMH5L3IwGRHKipmXTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});